### ISSUE TITLE
Charter only listens on localhost!

### ISSUE THREAD

**Issue by fsedano** [pbosetti/Charter#2]
After failing to communicate from outside world, I noticed charter is only binding to 127.0.0.1, preventing outside world communication!

Mac-Pro-de-Francisco:Downloads fsedano$ netstat  -an | grep 2001
udp4       0      0  127.0.0.1.2001         _._

**Comment by pbosetti** [comment]
Thanks for the notice.
I have a bug fix release ready for that, but due to ongoing changes in Apple's app store policies I am having some trouble updating the app store version. Meanwhile, you can download it from here: https://github.com/pbosetti/Charter/downloads

**Comment by fsedano** [comment]
Tnx!
